package com.socialapp.models

data class ApiMessage(
    val ok: Boolean? = null,
    val message: String? = null,
    val url: String? = null,
    val file_url: String? = null,
    val token: String? = null,
    val access_token: String? = null,
    val refresh_token: String? = null,
    val expires_in_minutes: Int? = null,
    val refresh_expires_in_days: Int? = null,
    val user: String? = null,
    val username: String? = null,
    val email: String? = null,
    val avatar: String? = null,
    val id: Int? = null,
    val role: String? = null,
    val permissions: List<String>? = null,
    val room_id: String? = null,
    val host: String? = null,
    val livekit_room: String? = null,
    val livekit_url: String? = null,
    val error: String? = null,
    val status: String? = null,
    val is_online: Boolean? = null,
    val last_seen: String? = null,
    val room_name: String? = null,
    val receiver: String? = null,
    val call_type: String? = null,
    val email_verification_required: Boolean? = null,
    val dev_verification_code: String? = null,
    val dev_reset_code: String? = null,
)
