export const PLATFORM_FEATURES = {
  explorePage: true,
  trendingPage: true,
  savedCollections: true,
  bookmarks: true,
  creatorStudio: true,
  monetization: true,
  adsManager: true,
  verificationSystem: true,
  translationSystem: true,
  accessibilitySupport: true,
  featureFlags: true,
  abTesting: true,
  crashAnalytics: true,
  errorReportingDashboard: true,
  cdnMediaPipeline: true,
  analyticsDashboards: true,
  userInsights: true,
  creatorInsights: true,
  businessAccounts: true,
  darkMode: true,
  themesSystem: true,
  onboardingFlow: true,
  tutorialSystem: true,
  referralSystem: true,
  achievementsSystem: true,
  badgesSystem: true,
  multiLanguageSupport: true,
  seoOptimization: true,
  ssrOptimization: true,
  sitemapGeneration: true,
  structuredMetadata: true,
  legalPrivacyFlows: true,
  consentManagement: true,
  copyrightReporting: true,
  takedownWorkflows: true,
};

export default PLATFORM_FEATURES;