import API from './axios.js';

export const getLiveRooms = () => API.get('/live_rooms', { cache: false, forceRefresh: true });
export const getLiveRoom = (roomId) => API.get(`/live_room/${roomId}`, { cache: false, forceRefresh: true });
export const createLiveRoom = (data) => API.post('/create_live', data);
export const getLiveToken = (payload) => API.post('/live_token', payload);
export const createCallToken = (payload) => API.post('/create_call_token', payload);
export const getLiveComments = (roomId) => API.get(`/live_comments/${roomId}`, { cache: false, forceRefresh: true });
export const updateLivePresence = (payload) => API.post('/live_presence', payload);
export const endLiveRoom = (roomId) => API.post(`/end_live/${roomId}`);
export const sendLiveReaction = (payload) => API.post('/live_reaction', payload);
export const sendLiveGift = (payload) => API.post('/live_gift', payload);
export const createLivePoll = (payload) => API.post('/live_poll', payload);
export const voteLivePoll = (pollId, payload) => API.post(`/live_poll/${pollId}/vote`, payload);
export const shareLiveRoom = (payload) => API.post('/live_share', payload);
export const addLiveCohost = (payload) => API.post('/live_cohost', payload);
export const startLiveBattle = (payload) => API.post('/live_battle', payload);
export const moderateLiveUser = (payload) => API.post('/live_moderation', payload);
export const updateLiveHealth = (payload) => API.post('/live_health', payload);
export const updateLiveRecording = (payload) => API.post('/live_recording', payload);
export const getLiveDashboard = (roomId) => API.get('/live_dashboard', { params: { room_id: roomId }, cache: false, forceRefresh: true });
export const getMyLiveSchedule = () => API.get('/live_schedule', { cache: false, forceRefresh: true });
