apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: app-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: your-dockerhub-username/user-service:latest
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: yamshat-config
            - secretRef:
                name: yamshat-secrets
          env:
            - name: SERVICE_NAME
              value: user-service
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: app-prod
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8000
      targetPort: http
      name: http
