export const LIVE_FEATURE_MATRIX = {
  liveStreaming: true,
  liveRooms: true,
  coHosting: true,
  guestSystem: true,
  liveComments: true,
  liveReactions: true,
  liveModeration: true,
  realtimeViewerCount: true,
  streamHealthMonitor: true,
  bitrateAdaptation: true,
  reconnectRecovery: true,
  replaySystem: true,
  clipGeneration: true,
  streamRecording: true,
  notifications: true,
  liveDiscovery: true,
  liveRecommendations: true,
  monetization: true,
  giftsSystem: true,
  subscriptions: true,
  streamAnalytics: true,
  streamReports: true,
  antiSpam: true,
  antiRaidSystem: true,
  streamQualityControls: true,
  mobileStreamingOptimization: true,
};

export default LIVE_FEATURE_MATRIX;