apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: app-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: your-dockerhub-username/chat-service:latest
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: yamshat-config
            - secretRef:
                name: yamshat-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: app-prod
  labels:
    app: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - port: 8000
      targetPort: http
      name: http
