export const CHAT_FEATURE_MATRIX = {
  realtimeMessaging: true,
  typingIndicator: true,
  readReceipts: true,
  deliveredStatus: true,
  onlinePresence: true,
  lastSeen: true,
  unreadBadges: true,
  messageReactions: true,
  replyMessages: true,
  forwardMessages: true,
  editMessages: true,
  deleteForEveryone: true,
  voiceNotes: true,
  videoMessages: true,
  fileUploads: true,
  imageCompression: true,
  videoCompression: true,
  uploadManager: true,
  resendFailedMessages: true,
  messageSearch: true,
  pinnedChats: true,
  archivedChats: true,
  muteConversations: true,
  blockUsers: true,
  spamFiltering: true,
  encryptionVerificationUI: true,
  disappearingMessages: true,
  groupChats: true,
  adminRoles: true,
  messageScheduling: true,
  chatThemes: true,
  stickers: true,
  gifSupport: true,
  voiceCalls: true,
  videoCalls: true,
  screenSharing: true,
  webrtcOptimization: true,
  reconnectRecovery: true,
  syncAcrossDevices: true,
  backupExportChat: true,
  messageStatusSync: true,
  offlineSync: true,
};

export default CHAT_FEATURE_MATRIX;